name: groupChat
main: com.davidhurng.helloplugin.groupChat
version: 1.0

commands:
  alt:
    description: alternative text
  
  mkch:
    description: create channel  
  
  join:
    description: join channel

  m:
    description: message channel

  block:
    description: block player
